Stud/urls.py
from django.urls import include

from django.contrib.auth.views import LoginView, LogoutView

from .import views
from django.contrib import admin
from django.urls import path
from .import Hod_views, views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin', admin.site.urls),
    path('base', views.Base, name='base'),
    path('home', Hod_views.Home, name='home'),
    # path('foncier_home', Staff_views.Home, name='foncier_home'),
    # profile
    path('', views.Accueil, name='acceueil'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('peche/', views.peche, name="peche"),
    path('post/<int:id>/', views.detail, name="detail"),
    path('post/', views.all, name="post"),
    path('new_post', views.new_post, name="new_post"),
    path('update_post/<int:pk>/', views.update_post, name="update_post"),
    path('delete_post/<int:id>/', views.delete_post, name="delete_post"),

    path('ressource/', views.ress, name="ressource"),
    path('upda_res/<int:id>/', views.upda_ress, name="upda_res"),
    path('delete_ress/<int:id>/', views.del_ress, name="delete_ress"),


    path('gestionnaire', views.coord, name='gestionnaire'),
    path('decideur', views.deci, name='decideur'),
    path('visiteur', views.visit, name='visiteur'),
    # end login
    path('profile_list/', views.profile_list, name='profile_list'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('profile_detail/', views.profile_detail, name='profile_detail'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('commune', views.commune, name='commune'),
    path('commune_detail', views.co, name='commune_detail'),
    path('peche/', include('peche.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peche/urls.py
from django.urls import path

from peche import views


app_name = 'peche'


urlpatterns = [
    path('pch/', views.pcount, name='pch'),
    path('dimpecart/', views.pec_art, name='dimpecart'),
    path('dimpecass/', views.pech_assu, name='dimpecass'),
    path('dimpecec/', views.pech_ec, name='dimpecec'),
    path('dimpecfin/', views.pech_fin, name='dimpecfin'),
    path('up_ar<int:id>/', views.update_ar, name='up_ar'),
    path('de_ar<int:id>/', views.delete_ar, name='de_ar'),
    path('up_ass<int:id>/', views.update_ass, name='up_ass'),
    path('de_ass<int:id>/', views.delete_ass, name='de_ass'),
    path('up_fin<int:id>/', views.update_fin, name='up_fin'),
    path('de_fin<int:id>/', views.delete_fin, name='de_fin'),
    path('up_com<int:id>/', views.update_com, name='up_com'),
    path('de_com<int:id>/', views.delete_com, name='de_com'),
    # ath('dimagroog/',views.dimagroorg_form,name='dimagroorg'),
    path('pech_ino/', views.pech_inov, name='pech_ino'),
    path('up_ino<int:id>/', views.update_ino, name='up_ino'),
    path('de_ino<int:id>/', views.delete_ino, name='de_ino'),
    path('pech_trans/', views.pechtrans, name='pech_trans'),
    path('update_trs<int:id>/', views.update_trs, name='update_trs'),
    path('delete_trs<int:id>/', views.delete_trs, name='delete_trs'),
    path('pech_taassu/', views.pechtassu, name='pech_taassu'),
    path('up_tassu<int:id>/', views.update_tassu, name='up_tassu'),
    path('de_tassu<int:id>/', views.delete_tasuu, name='de_tassu'),
    path('pech_tacom/', views.petacom, name='pech_tacom'),
    path('up_tc<int:id>/', views.update_tacom, name='up_tc'),
    path('de_tc<int:id>/', views.delete_tacom, name='de_tc'),
    path('pech_taino/', views.pech_tainov, name='pech_taino'),
    path('up_taino<int:id>/', views.up_taino, name='up_taino'),
    path('de_taino<int:id>/', views.de_taino, name='de_taino'),
    path('pech_tafina/', views.pechtafina, name='pech_tafina'),
    path('up_fi<int:id>/', views.up_fina, name='up_fi'),
    path('de_fi<int:id>/', views.de_fina, name='de_fi'),


]

peche/views.py
from django.shortcuts import render, redirect

from django.contrib import messages
from peche.DimPecheInnovat import pecino
from peche.PechTAAssurance import petttassu
from peche.PechTACommerc import pectom
from peche.PechTAFinance import pectafina
from peche.PechTransformArtisan import pectranf
from peche.PecheTAInnovation import pectaino

from peche.dimpechear import DPA
from peche.dimpecheas import DPAS
from peche.dimpechecom import DPC
from peche.dimpechefi import DPFI

from peche.models import DimPechTAAssurance, DimPechTACommerc, DimPechTAFinance, DimPechTransformArtisan, DimPecheArtisan, DimPecheAssure, DimPecheCommerce, DimPecheFinance, DimPecheInnovat, DimPecheTAInnovat

# Create your views here.


def pec_art(request):
    if request.method == 'POST':
        form = DPA(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/dimpecart/')
    else:
        form = DPA()
        return render(request, 'peche/dimpecheart.html', {'form': form, 'dataObject': DimPecheArtisan.objects.all()})


# update art
def update_ar(request, id):
    dataObject = DimPecheArtisan.objects.get(id=id)
    form = DPA(instance=dataObject)
    if request.method == 'POST':
        form = DPA(request.POST, instance=dataObject)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/dimpecart/')

    context = {

        'form': form

    }
    return render(request, 'peche/dimpecheart.html', context)


def delete_ar(request, id):
    dataObject = DimPecheArtisan.objects.get(id=id)
    if request.method == 'POST':
        dataObject.delete()
        return redirect('/peche/dimpecart/')
    context = {

        'item': dataObject, }
    return render(request, 'peche/delete_ar.html', context)


def pech_assu(request):
    if request.method == 'POST':
        form = DPAS(request.POST)
        if form.is_valid():

            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/dimpecass/')
    else:
        form = DPAS()

        return render(request, 'peche/dimpecheass.html', {'form': form, 'dataObject': DimPecheAssure.objects.all()})


# update ass
def update_ass(request, id):
    dataOd = DimPecheAssure.objects.get(id=id)
    form = DPAS(instance=dataOd)
    if request.method == 'POST':
        form = DPAS(request.POST, instance=dataOd)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/dimpecass/')

    context = {

        'form': form,

    }
    return render(request, 'peche/dimpecheass.html', context)


def delete_ass(request, id):
    dataOd = DimPecheAssure.objects.get(id=id)
    if request.method == 'POST':
        dataOd.delete()
        return redirect('/peche/dimpecass/')
    context = {

        'item': dataOd, }
    return render(request, 'peche/delete_ass.html', context)


def pech_fin(request):
    if request.method == 'POST':
        form = DPFI(request.POST)
        if form.is_valid():

            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/dimpecfin/')
    else:
        form = DPFI()

        return render(request, 'peche/dimpechefin.html', {'form': form, 'dataObject': DimPecheFinance.objects.all()})


# update finace
def update_fin(request, id):
    dataOf = DimPecheFinance.objects.get(id=id)
    form = DPFI(instance=dataOf)
    if request.method == 'POST':
        form = DPFI(request.POST, instance=dataOf)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/dimpecfin/')

    context = {

        'form': form,

    }
    return render(request, 'peche/dimpechefin.html', context)


def delete_fin(request, id):
    dataOf = DimPecheFinance.objects.get(id=id)
    if request.method == 'POST':
        dataOf.delete()
        return redirect('/peche/dimpecfin/')
    context = {

        'item': dataOf, }
    return render(request, 'peche/delete_fin.html', context)


def pech_ec(request):
    if request.method == 'POST':
        form = DPC(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/dimpecec/')
    else:
        form = DPC()
        return render(request, 'peche/dimpechecomm.html', {'form': form, 'dataObject': DimPecheCommerce.objects.all()})


# update commm
def update_com(request, id):
    dataOC = DimPecheCommerce.objects.get(id=id)
    form = DPC(instance=dataOC)
    if request.method == 'POST':
        form = DPC(request.POST, instance=dataOC)
        if form.is_valid():
            messages.success(request, " Are Successfully Added !")
            form.save()
            return redirect('/peche/dimpecec/')

    context = {

        'form': form,

    }
    return render(request, 'peche/dimpechecomm.html', context)


def delete_com(request, id):
    dataOC = DimPecheCommerce.objects.get(id=id)
    if request.method == 'POST':
        dataOC.delete()
        return redirect('/peche/dimpecec/')
    context = {

        'item': dataOC, }
    return render(request, 'peche/delete_com.html', context)


def pech_inov(request):
    if request.method == 'POST':
        form = pecino(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/pech_ino/')
    else:
        form = pecino()
        return render(request, 'peche/peche_ino.html', {'form': form, 'dataObject': DimPecheInnovat.objects.all()})


# update commm
def update_ino(request, id):
    dataOC = DimPecheInnovat.objects.get(id=id)
    form = pecino(instance=dataOC)
    if request.method == 'POST':
        form = pecino(request.POST, instance=dataOC)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/pech_ino/')

    context = {

        'form': form,

    }
    return render(request, 'peche/peche_ino.html', context)


def delete_ino(request, id):
    dataOC = DimPecheInnovat.objects.get(id=id)
    if request.method == 'POST':
        dataOC.delete()
        return redirect('/peche/pech_ino/')
    context = {

        'item': dataOC, }
    return render(request, 'peche/delete_ino.html', context)


# peche trans

def pechtrans(request):
    if request.method == 'POST':
        form = pectranf(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/pech_trans/')
    else:
        form = pectranf()
        return render(request, 'peche/peche_transf.html', {'form': form, 'dataObject': DimPechTransformArtisan.objects.all()})


# update commm
def update_trs(request, id):
    dataOC = DimPechTransformArtisan.objects.get(id=id)
    form = pectranf(instance=dataOC)
    if request.method == 'POST':
        form = pectranf(request.POST, instance=dataOC)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/pech_trans/')

    context = {

        'form': form,

    }
    return render(request, 'peche/peche_transf.html', context)


def delete_trs(request, id):
    dataOC = DimPechTransformArtisan.objects.get(id=id)
    if request.method == 'POST':
        dataOC.delete()
        return redirect('/peche/pech_trans/')
    context = {

        'item': dataOC, }
    return render(request, 'peche/delete_trans.html', context)


# pechetaassu

def pechtassu(request):
    if request.method == 'POST':
        form = petttassu(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/pech_taassu/')
    else:
        form = petttassu()
        return render(request, 'peche/peche_tass.html', {'form': form, 'dataObject': DimPechTAAssurance.objects.all()})


# update commm
def update_tassu(request, id):
    dataOC = DimPechTAAssurance.objects.get(id=id)
    form = petttassu(instance=dataOC)
    if request.method == 'POST':
        form = petttassu(request.POST, instance=dataOC)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/pech_taassu/')

    context = {

        'form': form,

    }
    return render(request, 'peche/peche_tass.html', context)


def delete_tasuu(request, id):
    dataOC = DimPechTAAssurance.objects.get(id=id)
    if request.method == 'POST':
        dataOC.delete()
        return redirect('/peche/pech_taassu/')
    context = {

        'item': dataOC, }
    return render(request, 'peche/delete_taassu.html', context)


# pechet

def petacom(request):
    if request.method == 'POST':

        form = pectom(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/pech_tacom/')
    else:
        form = pectom()
        return render(request, 'peche/peche_tacom.html', {'form': form, 'dataObject': DimPechTACommerc.objects.all()})


# update commm
def update_tacom(request, id):
    dataObject = DimPechTACommerc.objects.get(id=id)
    form = pectom(instance=dataObject)
    if request.method == 'POST':
        form = pectom(request.POST, instance=dataObject)
        if form.is_valid():
            form.save()
            messages.success(request, " Are Successfully Added !")
            return redirect('/peche/pech_tacom/')

    context = {

        'form': form,

    }

peche/templates/peche/delete_ar.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
            </div>
         </div>
      </div>
      <section class="hero is-dark is-fullheight">
        <div class="hero-body">
          <div class="container" style =" padding-left: 250px;">
            <div class="columns is-centered">

                        

                                        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                                              <div class="bg-light rounded h-100 p-4">
                                              <div class="card card-body">
                                            <h5>Voulez-vous supprimer cette enregistrement</h5>
                                          <form action="{% url 'peche:de_ar' item.id %}" method="Post">
                                                  {% csrf_token %}
                                                 <a class="btn btn-warning" href="{% url 'peche:dimpecart'%}">Annuler</a>
                                                    <input class="btn btn-danger" type="submit" name="Supprimer">
                                          </form>
                                       </div>
                                      </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                 </section>
<div >
 </div>
   
</div>
{% endblock %}	

peche/templates/peche/delete_com.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
            </div>
         </div>
      </div>
      <section class="hero is-dark is-fullheight">
        <div class="hero-body">
          <div class="container" style =" padding-left: 250px;">
            <div class="columns is-centered">


                                        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                                              <div class="bg-light rounded h-100 p-4">
                                              <div class="card card-body">
                                            <h5>Voulez-vous supprimer cette enregistrement</h5>
                                          <form action="{% url 'peche:de_com' item.id %}" method="Post">
                                                  {% csrf_token %}
                                                 <a class="btn btn-warning" href="{% url 'peche:dimpecec'%}">Annuler</a>
                                                    <input class="btn btn-danger" type="submit" name="Supprimer">
                                          </form>
                                       </div>
                                      </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                          </section>
<div >
 </div>
   
</div>
{% endblock %}	

peche/templates/peche/delete_ino.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
            </div>
         </div>
      </div>
      <section class="hero is-dark is-fullheight">
        <div class="hero-body">
          <div class="container" style =" padding-left: 250px;">
            <div class="columns is-centered">

                        

                                        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                                              <div class="bg-light rounded h-100 p-4">
                                              <div class="card card-body">
                                            <h5>Voulez-vous supprimer cette enregistrement</h5>
                                          <form action="{% url 'peche:de_ino' item.id %}" method="Post">
                                                  {% csrf_token %}
                                                 <a class="btn btn-warning" href="{% url 'peche:pech_ino'%}">Annuler</a>
                                                    <input class="btn btn-danger" type="submit" name="Supprimer">
                                          </form>
                                       </div>
                                      </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                 </section>
<div >
 </div>
   
</div>
{% endblock %}	

peche/templates/peche/delete_taassu.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
            </div>
         </div>
      </div>
      <section class="hero is-dark is-fullheight">
        <div class="hero-body">
          <div class="container" style =" padding-left: 250px;">
            <div class="columns is-centered">

                        

                                        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                                              <div class="bg-light rounded h-100 p-4">
                                              <div class="card card-body">
                                            <h5>Voulez-vous supprimer cette enregistrement</h5>
                                          <form action="{% url 'peche:de_tassu' item.id %}" method="Post">
                                                  {% csrf_token %}
                                                 <a class="btn btn-warning" href="{% url 'peche:pech_taassu'%}">Annuler</a>
                                                    <input class="btn btn-danger" type="submit" name="Supprimer">
                                          </form>
                                       </div>
                                      </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                 </section>
<div >
 </div>
   
</div>
{% endblock %}	

peche/templates/peche/delete_taino.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
            </div>
         </div>
      </div>
      <section class="hero is-dark is-fullheight">
        <div class="hero-body">
          <div class="container" style =" padding-left: 250px;">
            <div class="columns is-centered">

                        

                                        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                                              <div class="bg-light rounded h-100 p-4">
                                              <div class="card card-body">
                                            <h5>Voulez-vous supprimer cette enregistrement</h5>
                                          <form action="{% url 'peche:de_taino' item.id %}" method="Post">
                                                  {% csrf_token %}
                                                 <a class="btn btn-warning" href="{% url 'peche:pech_taino'%}">Annuler</a>
                                                    <input class="btn btn-danger" type="submit" name="Supprimer">
                                          </form>
                                       </div>
                                      </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                 </section>
<div >
 </div>
   
</div>
{% endblock %}	

peche/templates/peche/delete_trans.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
            </div>
         </div>
      </div>
      <section class="hero is-dark is-fullheight">
        <div class="hero-body">
          <div class="container" style =" padding-left: 250px;">
            <div class="columns is-centered">

                        

                                        <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                                              <div class="bg-light rounded h-100 p-4">
                                              <div class="card card-body">
                                            <h5>Voulez-vous supprimer cette enregistrement</h5>
                                          <form action="{% url 'peche:delete_trs' item.id %}" method="Post">
                                                  {% csrf_token %}
                                                 <a class="btn btn-warning" href="{% url 'peche:pech_trans'%}">Annuler</a>
                                                    <input class="btn btn-danger" type="submit" name="Supprimer">
                                          </form>
                                       </div>
                                      </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                 </section>
<div >
 </div>
   
</div>
{% endblock %}	

peche/templates/peche/dimpecheass.html
{% extends 'pages/base.html' %}
{% load static %}

{% block content %}
<div class="page-wrapper">
   <div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body">
               <form method="post" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                     <div class="col-12">
                        <h5 class="form-title"><span>Formulaire dimension Peche Assurance</span></h5>
                     </div>

                     {% include 'includes/messages.html' %}	

                    
                           
                           {{ form.as_p}}
               
                   
					
					 
					      
                     
                     
		 
            </div>
                  
                   <br>
                     <div class="col-12">
                        <button type="submit" class="btn btn-primary">Ajouter</button>
                     </div>

               </form>
            </div>
         </div>
      </div>
      
<div >
 <div class="content container-fluid">
   <div class="page-header">
      <div class="row align-items-center">
      </div>
   </div>
   {% include 'includes/messages.html' %}
   <div class="row">
      <div class="col-sm-12">
         <div class="card card-table">
            <div class="card-body">
               <div class="table-responsive">
                  <table id="table_id" class="table table-hover table-center mb-0">
                     <thead>
                        <tr>
                           <th>Id</th>
                           <th>codeCommune</th>
                           <th>nomCommune</th>
                           <th>OffreAssureExistPech</th>
                           <th>TypeAssurancPech</th>
                           <th>NbreSouscripPech</th>
                           <th>NbrePrimePech</th>
                           <th>BesoinFormatPech</th>
                           <th>ActeurSensibilisePech</th>
                           <th>ActeurFormatPech</th>
                           <th>BesoinSensibilisePech</th>
                           <th>ContraintGlobPech</th>
                           <th>ContrainMajFilier</th>
                           <th>NbrInfrastruStokCondition</th>
                           <th>NbrFourniEmblag</th>
                           <th>NbrProdLabel</th>
                           <th>Date Début</th>
                           <th>Date de Modification</th>
                           <th class="text-right">Action</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for stud in dataObject %}
                        <tr>
                         
                           <td>{{ stud.id}}</td>
                           <td>{{ stud.codeCommune }}</td>	
                           <td>{{ stud.nomCommune }}</td>	
                           <td>{{ stud.OffreAssureExistPech }}</td>	
                           <td>{{ stud.TypeAssurancPech }}</td>	
                           <td>{{ stud.NbreSouscripPech }}</td>	
                           <td>{{ stud.NbrePrimePech }}</td>	
                           <td>{{ stud.BesoinFormatPech }}</td>	
                           <td>{{ stud.ActeurSensibilisePech }}</td>	
                           <td>{{ stud.ActeurFormatPech }}</td>	
                           <td>{{ stud.BesoinSensibilisePech }}</td>	
                           <td>{{ stud.ContraintGlobPech }}</td>	
                           <td>{{ stud.ContrainMajFilier }}</td>	
                           <td>{{ stud.NbrInfrastruStokCondition }}</td>	
                           <td>{{ stud.NbrFourniEmblag }}</td>	
                           <td>{{ stud.NbrProdLabel }}</td>	
                           <td>{{ stud.date }}</td>
                           <td>{{ stud.date_modification }}</td>		
                           <td class="text-right">
                              <div class="actions">
                                 <a href="{% url 'peche:up_ass' stud.id %}" class="btn btn-sm bg-success-light mr-2">
                                 <i class="fas fa-pen"></i>
                                 </a>
                                 <a href="{% url 'peche:de_ass' stud.id %}" class="btn btn-sm bg-danger-light">
                                 <i class="fas fa-trash"></i>
                                 </a>
                              </div>
                           </td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>

   
</div>
{% endblock %}	