Stud/urls.py
from django.urls import include

from django.contrib.auth.views import LoginView, LogoutView

from .import views
from django.contrib import admin
from django.urls import path
from .import Hod_views, views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin', admin.site.urls),
    path('base', views.Base, name='base'),
    path('home', Hod_views.Home, name='home'),
    # path('foncier_home', Staff_views.Home, name='foncier_home'),
    # profile
    path('', views.Accueil, name='acceueil'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('peche/', views.peche, name="peche"),
    path('post/<int:id>/', views.detail, name="detail"),
    path('post/', views.all, name="post"),
    path('new_post', views.new_post, name="new_post"),
    path('update_post/<int:pk>/', views.update_post, name="update_post"),
    path('delete_post/<int:id>/', views.delete_post, name="delete_post"),

    path('ressource/', views.ress, name="ressource"),
    path('upda_res/<int:id>/', views.upda_ress, name="upda_res"),
    path('delete_ress/<int:id>/', views.del_ress, name="delete_ress"),


    path('gestionnaire', views.coord, name='gestionnaire'),
    path('decideur', views.deci, name='decideur'),
    path('visiteur', views.visit, name='visiteur'),
    # end login
    path('profile_list/', views.profile_list, name='profile_list'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('profile_detail/', views.profile_detail, name='profile_detail'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('commune', views.commune, name='commune'),
    path('commune_detail', views.co, name='commune_detail'),
    path('peche/', include('peche.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peche/urls.py
from django.urls import path

from peche import views


app_name = 'peche'


urlpatterns = [
    path('pch/', views.pcount, name='pch'),
    path('dimpecart/', views.pec_art, name='dimpecart'),
    path('dimpecass/', views.pech_assu, name='dimpecass'),
    path('dimpecec/', views.pech_ec, name='dimpecec'),
    path('dimpecfin/', views.pech_fin, name='dimpecfin'),
    path('up_ar<int:id>/', views.update_ar, name='up_ar'),
    path('de_ar<int:id>/', views.delete_ar, name='de_ar'),
    path('up_ass<int:id>/', views.update_ass, name='up_ass'),
    path('de_ass<int:id>/', views.delete_ass, name='de_ass'),
    path('up_fin<int:id>/', views.update_fin, name='up_fin'),
    path('de_fin<int:id>/', views.delete_fin, name='de_fin'),
    path('up_com<int:id>/', views.update_com, name='up_com'),
    path('de_com<int:id>/', views.delete_com, name='de_com'),
    # ath('dimagroog/',views.dimagroorg_form,name='dimagroorg'),
    path('pech_ino/', views.pech_inov, name='pech_ino'),
    path('up_ino<int:id>/', views.update_ino, name='up_ino'),
    path('de_ino<int:id>/', views.delete_ino, name='de_ino'),
    path('pech_trans/', views.pechtrans, name='pech_trans'),
    path('update_trs<int:id>/', views.update_trs, name='update_trs'),
    path('delete_trs<int:id>/', views.delete_trs, name='delete_trs'),
    path('pech_taassu/', views.pechtassu, name='pech_taassu'),
    path('up_tassu<int:id>/', views.update_tassu, name='up_tassu'),
    path('de_tassu<int:id>/', views.delete_tasuu, name='de_tassu'),
    path('pech_tacom/', views.petacom, name='pech_tacom'),
    path('up_tc<int:id>/', views.update_tacom, name='up_tc'),
    path('de_tc<int:id>/', views.delete_tacom, name='de_tc'),
    path('pech_taino/', views.pech_tainov, name='pech_taino'),
    path('up_taino<int:id>/', views.up_taino, name='up_taino'),
    path('de_taino<int:id>/', views.de_taino, name='de_taino'),
    path('pech_tafina/', views.pechtafina, name='pech_tafina'),
    path('up_fi<int:id>/', views.up_fina, name='up_fi'),
    path('de_fi<int:id>/', views.de_fina, name='de_fi'),


]

templates/includes/chart.html
<script>
  'use strict';
  $(document).ready(function() {

    var options = {
      series: [{{peche}}, {{pfina}},{{peche}}, {{pfina}}],
      chart: {
        height: 350,
        width: '100%',
      type: 'donut',
    },
    plotOptions: {
      pie: {
        startAngle: -90,
        endAngle: 270
      }
    },
    dataLabels: {
      enabled: false
    },
    fill: {
      type: 'gradient',
    },
    legend: {
      formatter: function(val, opts) {
        return val + " - " + opts.w.globals.series[opts.seriesIndex]
      }
    },

    responsive: [{
      breakpoint: 480,
      options: {
        chart: {
          height: 350,
          width: '100%',
        },
        legend: {
          position: 'bottom'
        }
      }
    }]
    };

    var chart = new ApexCharts(document.querySelector("#c"), options);
    chart.render();



      var options = {
          series: [{{peche}}, {{pfina}}, {{peino}}, {{pcom}}],
          chart: {
            height: 350,
            width: '100%',
          type: 'pie',
        },
        labels: ['Peche Finance', 'Peche Artisan', 'Peche Commerce', 'Peche Innovation'],
        responsive: [{
          breakpoint: 480,
          options: {
            chart: {
              height: 350,
              width: '100%',
            },
            legend: {
              position: 'bottom'
            }
          }
        }]
        };

        var chart = new ApexCharts(document.querySelector("#all_details"), options);
        chart.render();




      if ($('#stud_gender').length > 0) {
          var optionsBar = {
              chart: {
                  type: 'bar',
                  height: 350,
                  width: '100%',
                  stacked: true,
                  toolbar: {
                      show: false
                  },
              },
              dataLabels: {
                  enabled: false
              },
              plotOptions: {
                  bar: {
                      columnWidth: '45%',
                  }
              },
              series: [
              {
                  name: "Peche Artisan",
                  color: '#fdbb38',
                  data: [{{peche}}],
              },


              {
                  name: "Peche Finance",
                  color: '#18affb',
                  data: [{{pfina}}],
              },
              
              {
                  name: "Peche Commerce",
                  color: '#59a11a',
                  data: [{{pcom}}],
              },
                {
                  name: "Peche Innovation",
                  color: '#a1371a',
                  data: [{{peino}}],
              }],
              labels: [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
              xaxis: {
                  labels: {
                      show: false
                  },
                  axisBorder: {
                      show: false
                  },
                  axisTicks: {
                      show: false
                  },
              },
              yaxis: {
                  axisBorder: {
                      show: false
                  },
                  axisTicks: {
                      show: false
                  },
                  labels: {
                      style: {
                          colors: '#777'
                      }
                  }
              },
              title: {
                  text: '',
                  align: 'left',
                  style: {
                      fontSize: '18px'
                  }
              }

          }

          var chartBar = new ApexCharts(document.querySelector('#stud_gender'), optionsBar);
          chartBar.render();
          }


      var options = {
          series:  [{{peche}}, {{pfina}}, {{peino}}, {{pcom}}],
          chart: {
            height: 350,
            width: '100%',
          type: 'scatter',
        },
        plotOptions: {
          pie: {
            startAngle: -90,
            endAngle: 270
          }
        },
        dataLabels: {
          enabled: false
        },
        fill: {
          type: 'gradient',
        },
        legend: {
          formatter: function(val, opts) {
            return val + " - " + opts.w.globals.series[opts.seriesIndex]
          }
        },

        responsive: [{
          breakpoint: 480,
          options: {
            chart: {
              height: 350,
        width: '100%',
            },
            legend: {
              position: 'bottom'
            }
          }
        }]
        };

        var chart = new ApexCharts(document.querySelector("#all"), options);
        chart.render();

  });

</script>

templates/includes/footer.html
{% load static %}
<footer style="background-color: #000">
    <div class="row">
      
       
        <div class="col-xl-4 col-sm-6 col-12">
           <div class="">
            <a href="/" class="logo">
                <img src=" {% static 'assets/img/log.jpg ' %}" alt="Logo">
            </a>
            <p style="color: #fff">Copyright © 2022<br> Precvadi ENSAIGT.</p>
           </div>
          
        </div>
        <div class="col-xl-4 col-sm-6 col-12">
            <div  class="">
               <p  style="color: #fff">Nombre de visiteur: {{ request.session.visits }}</p><br><br>
               <h6><p  style="color: #fff">Mairie de Joal-Fadiouth</p></h6>
               <p  style="color: #fff"><i class="fa-regular fa-envelope"></i> &nbsp;&nbsp;communejf@yahoo.com</p>
               <p  style="color: #fff"><i class="fa-solid fa-phone"></i>&nbsp;&nbsp;+221 33 957 61 04</p>
            </div>
         </div>
        <div class="col-xl-4 col-sm-6 col-12">
           <div class="">
            <div class="column">
                <h3  style="color: #fff">Suivez-nous</h3>
                <ul style="color: #fff">
                  <li ><a href="#" style="color: #fff">Facebook</a></li>
                  <li ><a href="#" style="color: #fff">Twitter</a></li>
                  <li ><a href="#" style="color: #fff">Instagram</a></li>
                </ul>
              </div>
        </div>
     </div>
      

   
  </div>
 
</footer>

templates/includes/header.html
{% load static %}
<div class="header">
  <div class="header-left">
    <a href="{% url 'acceueil' %}" class="logo">
      <img src="{% static 'assets/img/logo.jpg' %}" alt="Logo" />
    </a>
    <a href="{% url 'acceueil' %}" class="logo logo-small">
      <img
        src="{% static 'assets/img/log.jpg' %}"
        alt="Logo"
        width="30"
        height="30"
      />
    </a>
  </div>
  <a href="javascript:void(0);" id="toggle_btn">
    <i class="fas fa-align-left"></i>
  </a>
  <div class="top-nav-search"></div>
  <a class="mobile_btn" id="mobile_btn">
    <i class="fas fa-bars"></i>
  </a>

  <ul class="nav user-menu">
    {% if not request.user.userprofile %}
    <li><a href="{% url 'create_profile' %}">Complétez votre Profil</a></li>
    {% endif %}
    <li class="nav-item dropdown has-arrow">
      <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
        <span class="user-img">
          <img
            src="{{ request.user.userprofile.profile_picture.url }}"
            alt="User Image"
            width="50"
            height="50"
          />
        </span>
      </a>
      <div class="dropdown-menu">
        <div class="user-header">
          <div class="avatar avatar-sm">
            <span class="user-img">
              <img
                src="{{ request.user.userprofile.profile_picture.url }}"
                alt="User Image"
                width="50"
                height="50"
              />
            </span>
          </div>
          <div class="user-text">
            <h6>
              {{ request.user.userprofile.first_name }}
              {{request.user.userprofile.last_name }}
            </h6>
          </div>
        </div>
        {% if not request.user.userprofile %}
        <a class="dropdown-item" href="{% url 'create_profile' %}"
          >Ajouter un Profil</a
        >
        {% else %}
        <a class="dropdown-item" href="{% url 'profile_list' %}">Profil</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'logout' %}">Se déconnecter</a>
      </div>
    </li>
  </ul>
</div>

templates/includes/messages.html
{% if messages %}
{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
   {{message}}
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
   <span aria-hidden="true">&times;</span>
   </button>
</div>
{% endif %}
{% endfor %}
{% endif %}
{% if messages %}
{% for message in messages %}
{% if message.tags == 'success' %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
   {{message}}
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
   <span aria-hidden="true">&times;</span>
   </button>
</div>
{% endif %}
{% endfor %}
{% endif %}
{% if messages %}
{% for message in messages %}
{% if message.tags == 'warning' %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   {{message}}
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
   <span aria-hidden="true">&times;</span>
   </button>
</div>
{% endif %}
{% endfor %}
{% endif %}                        
								
								
	

templates/includes/sidebar.html
{% load active_link_tags %}
{% load static %}
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
       <div id="sidebar-menu" class="sidebar-menu">

         <ul>
            <li class="menu-title">
               <span>{{user.username}} {{user.username}}</span>
            </li>
            <li class="menu-title">
               <span>Menu principal</span>
            </li>

            <li class="{% active_link 'home' 'active' %}">
              <a href="{% url 'home' %}"><img src="{% static '/imge/icon peche.png'%}" alt="logo" width="50" height="50"> <span style="font-size: 20px">Peche</span></a>
           </li>

        
         </ul>

         

         <ul>
         <li>
            
            
           <li class="submenu {% active_link 'peche:pch' 'active' %}{% active_link 'peche:pch' 'active' %}">
              
 

                  <li><a href="{% url 'peche:dimpecart'%}">Peche Artisan</a></li>
                  <li><a href="{% url 'peche:dimpecass'%}">Peche Assurance</a></li>
                  <li><a href="{% url 'peche:dimpecec'%}">Peche Commerce</a></li>
                  <li><a href="{% url 'peche:dimpecfin'%}">Peche Finance</a></li>
                  <li><a href="{% url 'peche:pech_ino'%}">Peche Innovation</a></li>
                  <li><a href="{% url 'peche:pech_taino'%}">Peche TA Innovation</a></li>
                  <li><a href="{% url 'peche:pech_trans'%}">Peche tranformation Artisan</a></li>
                  <li><a href="{% url 'peche:pech_taassu'%}">Peche TA Assurance</a></li>
                  <li><a href="{% url 'peche:pech_tacom'%}">Peche TA Commerce</a></li>
                  <li><a href="{% url 'peche:pech_tafina'%}">Peche TA Finance</a></li>
               
                  <li><i class=""></i>
                        <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> <span> Se déconnecter</span></a>
                  </li>
              
            </li>
      </li>
         </ul>

        

       </div>
    </div>
 </div>